### ISSUE TITLE
[ChosunTruck] 주변 물체인식 관련 해법

### ISSUE THREAD

**Issue by chi3236** [D2CAMPUS-FEST/2016#10]
현재 프로그램은 도로의 차선을 인식해여 차선을 맞춰 주행을 할 수 있는 단계이고
여기에서 더 나아가 차량 주변의 물체도 인식하여 주변환경에 대응하며 주행할 수 있도록 만들고 싶습니다.
현재 계획으로는 게임 화면에서 정보를 얻어 주변 차량의 형태나 크기를 분석하고 학습시켜서
그 차량의 종류를 알아내고 그에 대한 대응 주행방법을 마련하려 하는데
도움이 될 수 있는 알고리즘이나 툴, 라이브러리, 레퍼런스 등을 알고계시는 분들의 도움을 요청합니다.
도와주세요!

**Comment by punkyoon** [comment]
도움이 될 지 모르겠지만, 논문 링크 하나 남겨두겠습니다...!
http://ocean.kisti.re.kr/downfile/volume/kelects/KCTSAD/2013/v8n8/KCTSAD_2013_v8n8_1129.pdf

**Comment by chi3236** [comment]
해결되었습니다 감사합니다
