### ISSUE TITLE
★ [공지] 첫 번째 밋업 참가 신청 (2월 1일-수)

### ISSUE THREAD

**Issue by Kang-heesuk** [D2CAMPUS-FEST/2016#15]
2월 1일(수) D2 StartupFactory에서 첫 번째 밋업이 진행됩니다.

참가자 개별 프로젝트 진행과 다른 참가자들과 교류를 위해 만들어진 시간입니다.
오셔서 다른 참가자와 오프라인으로 논의도 하며, 팀의 이슈를 함께 해결해 볼 수 있어요!
참가자들의 기술 talk도 준비되어 있습니다 :)

일시 : 2월 1일(수), 오후 2시 - 7시
* 오후 2시 - 5시 : 자유롭게 프로젝트 개발 및 토론 (개발자 Café처럼)
* 오후 5시 - 7시 : Lightening Talk
  - Kokoto : MongoDB에서 RDBMS + Redis로 전환한 후의 성능 향상
  - Sherlock.py : Shellscript에 대해서

※ 첫 번째 밋업에 참여를 원하시는 분은 댓글 남겨주세요!

**Comment by g6123** [comment]
Kokoto팀 두 명 모두 참가합니다.
MongoDB에서 RDBMS + Redis로 전환한 후의 성능 향상에 관해서 발표하고 싶습니다.

**Comment by Luavis** [comment]
Sherlock.py팀 참가합니다.
"Shellscript에 대해서"를 짧게 발표하고 싶습니다.

**Comment by punkyoon** [comment]
coding-night-live
 - 정연준 :  잘 모르겠습니다... 거의 끝나갈때쯤 갈 수 있을 것 같습니다.
 - 최광희 : 참석합니다.
 - 하지윤 : 참석합니다.

**Comment by Kang-heesuk** [comment]
@g6123 @Luavis 네네 :) 아주아주 좋습니다 👍  발표 시간은 30분 이내로 준비 부탁드립니다!!

**Comment by lkaybob** [comment]
Weblockly 팀 전원 참석합니다!! :smile:

**Comment by hahnlee** [comment]
Tracer 가능 합니다 :)

**Comment by seokju-na** [comment]
girok팀 가능합니다~!

**Comment by Red-Portal** [comment]
Lighthouse 팀 가능합니다!

**Comment by bethesirius** [comment]
ChosunTruck 팀 참가합니다~ \(･ิω･ิ)ノ

**Comment by siosio34** [comment]
AR-Trace 팀 참가합니다.
조영제 : 참석
김만수 : 참석
김지현 : 참석불가

**Comment by g6123** [comment]
오늘 Kokoto 팀 발표 자료 공유합니다 ._.) /
http://www.slideshare.net/secret/wFEibajr2xQLrS

**Comment by Luavis** [comment]
오늘 발표자료 공유합니다 🎉
http://www.slideshare.net/luavis/shellscript-71624877
