### ISSUE TITLE
★ [공지] 두 번째 밋업 참가 신청 (2월 8일-수)

### ISSUE THREAD

**Issue by Kang-heesuk** [D2CAMPUS-FEST/2016#18]
2월 8일(수) D2 StartupFactory에서 두 번째 밋업이 진행됩니다.

참가자 개별 프로젝트 진행과 다른 참가자들과 교류를 위해 만들어진 시간입니다.
오셔서 다른 참가자와 오프라인으로 논의도 하며, 팀의 이슈를 함께 해결해 볼 수 있어요!

일시 : 2월 8일(수), 오후 2시 - 7시

오후 2시 - 5시 : 자유롭게 프로젝트 개발 및 토론 (개발자 Café처럼)
오후 5시 - 7시 : Lightning Talk
 - coding-night-live : Django에서 Websocket을 사용하는 방법 
 - Lighthouse : Google Protobuf + SWIG 를 이용한 성능 향상용 C++ 모듈 랩핑
 - Kokoto : 프론트엔드에서 React, CSS Modules, Translation
 - AR-Trace  : Firebase

※ 밋업에 참여를 원하시는 분은 댓글 남겨주세요!

**Comment by PJunhyuk** [comment]
crafty 팀 전원 참석 희망합니다!

**Comment by Luavis** [comment]
Sherlock.py팀 참가합니다.

**Comment by hahnlee** [comment]
Tracer 참가합니다

**Comment by Red-Portal** [comment]
Lighthouse 둘다 참석합니다
(자리가 있다면) Google Protobuf + SWIG 를 이용한 성능 향상용 C++ 모듈 랩핑에 관해 얘기를 하고 싶습니다.

**Comment by raon0211** [comment]
Kokoto 팀 참가합니다.
(자리가 있다면) Kokoto 팀 프론트엔드에서 React, CSS Modules, Translation과 관련한 간단한 이야기를 하고 싶습니다.

**Comment by siosio34** [comment]
AR-Trace 밋업 참가합니다.
그리고 밋업 발표도 파이어베이스에 관하여 발표를 하고 싶습니다.

**Comment by punkyoon** [comment]
Coding-Night-Live lightening talk 주제 공유드립니다.
주제는 **Django에서 Websocket을 사용하는 방법** 입니다. 감사합니다.

정연준 : 3~4시 사이에 참석할 것 같습니다.
최광희 : 참석합니다.
하지윤 : 참석합니다.

**Comment by Kang-heesuk** [comment]
@Red-Portal @raon0211 @siosio34 @PJunhyuk 
오오오 풍성한 talk 감사합니다 :) 발표 시간은 15분 정도로 준비 부탁드릴께요~ 
발표자료는 댓글로 남겨주세요!

**Comment by lkaybob** [comment]
늦어서 죄송합니다. Weblockly팀 일부 참석 예정입니다.

계성혁 : 참석
최홍범 : 미정
주현수 : 불참

**Comment by Luavis** [comment]
참가하고 싶었는데 교수님 면담이 잡혀서.. 빠져야할거 같아요 죄송합니다 ㅠ

**Comment by seokju-na** [comment]
Girok팀 참여합니다~!

**Comment by UnoRich** [comment]
늦었습니다. gimci 정원영 참석합니다

**Comment by Red-Portal** [comment]
발표자료입니다! 결승전 발표자료 올리라는게 이거인지 알고 잘못 올렸었네요...

[swig를 이용한 C++ 랩핑.pdf](https://github.com/D2CAMPUS-FEST/2016/files/760062/swig.C.pdf)

**Comment by punkyoon** [comment]
coding-night-live 발표자료입니다.

[django에서 websocket을 사용하는 방법](https://drive.google.com/open?id=0B5acoZNCGpvra2w0a25YSFFadXM)

**Comment by raon0211** [comment]
Kokoto 팀 발표자료입니다.

http://www.slideshare.net/ssuser9befac/20170202-d2
