### ISSUE TITLE
[Sherlock] 프로젝트명 및 라이선스 수정했습니다

### ISSUE THREAD

**Issue by mjkim610** [D2CAMPUS-FEST/2016#19]
저희 프로젝트명은 소문자 's'로 시작하는 sherlock입니다.
그리고 저희가 활용하는 프로젝트를 검토해본 결과 3-Clause BSD License를 사용해야할 것 같습니다.

다음 사항 수정해주시면 감사하겠습니다! :)

--------------------------------------
![image](https://cloud.githubusercontent.com/assets/17107206/22548481/e47fd326-e989-11e6-8ce9-2099d208763f.png)

**Comment by Kang-heesuk** [comment]
@mjkim610 넵 해당 부분 수정해두었습니다.  이후 수정사항에 대해서는 PR보내주시면 merge 하도록 하겠습니다.
