### ISSUE TITLE
결승전 발표자료를 취합합니다!

### ISSUE THREAD

**Issue by Kang-heesuk** [D2CAMPUS-FEST/2016#20]
17일 결승전 이전까지 발표자료를 댓글로 남겨주세요!
* 행사장의 wifi 사용이 불가합니다.

영상을 준비하신 경우 URL도 함께 남겨주세요.
폰트 깨짐 등을 방지 하기 위해 발표자료는 pdf형식으로 올려주시기 바랍니다.

* 파일용량 등의 제한이 있는 경우에는 slideshare의 url을 공유해주시거나 naver_d2@naver.com 으로 보내주세요~)

예제) [팀명] 발표자료() 및 URL

**Comment by Red-Portal** [comment]
Lighthouse 팀
[swig를 이용한 C++ 랩핑.pptx](https://github.com/D2CAMPUS-FEST/2016/files/758694/swig.C.pptx)

**Comment by kim-sardine** [comment]
1등! 발표자료 제출합니다~
[sherlock_edited.pdf](https://github.com/D2CAMPUS-FEST/2016/files/780570/sherlock_edited.pdf)
///2월17일 00시29분..
상당부분 수정했습니다.. 꼴등이네요

**Comment by lkaybob** [comment]
Weblockly팀 2등으로 제출합니다! :)
[Weblockly_Final.pdf](https://github.com/D2CAMPUS-FEST/2016/files/779820/Weblockly_Final.pdf)

**Comment by hahnlee** [comment]
Tracer팀 동메달 차지 합니다  🥉
 [Tracer.pdf](https://github.com/D2CAMPUS-FEST/2016/files/779831/Tracer.pdf)

**Comment by mingrammer** [comment]
pyreportcard팀 제출합니다.
[D2-FEST-PyReportCard-2017-02-17.pdf](https://github.com/D2CAMPUS-FEST/2016/files/779952/D2-FEST-PyReportCard-2017-02-17.pdf)

**Comment by Red-Portal** [comment]
[Lighthouse] 팀 제출합니다...
[Lighthouse_최종발표.pdf](https://github.com/D2CAMPUS-FEST/2016/files/779997/Lighthouse_.pdf)

**Comment by raon0211** [comment]
kokoto 팀 제출합니다!
[kokoto_PR.pdf](https://github.com/D2CAMPUS-FEST/2016/files/780277/kokoto_PR.pdf)

**Comment by chi3236** [comment]
ChosunTruck팀 제출합니다
[조선트럭 발표자료.pdf](https://github.com/D2CAMPUS-FEST/2016/files/780612/default.pdf)

**Comment by seokju-na** [comment]
girok팀 제출합니다.
[girok_발표자료.pdf](https://github.com/D2CAMPUS-FEST/2016/files/781143/girok.READ.pdf)
[girok.key.zip](https://github.com/D2CAMPUS-FEST/2016/files/782331/girok.key.zip)

**Comment by Luavis** [comment]
sherlock.py팀 제출합니다.

[sherlock.py.pdf](https://github.com/D2CAMPUS-FEST/2016/files/781646/sherlock.py.pdf)

**Comment by minwhoo** [comment]
crafty팀 제출합니다.
[crafty_D2_presentation_v1.pdf](https://github.com/D2CAMPUS-FEST/2016/files/781898/crafty_D2_presentation_v1.pdf)

**Comment by juice500ml** [comment]
coding-night-live 팀 제출합니다.
영상: https://youtu.be/EgOmuShXVNE
발표자료: [coding-night-live.pdf](https://github.com/D2CAMPUS-FEST/2016/files/781949/coding-night-live.pdf)

**Comment by Kang-heesuk** [comment]
10시 50분 기준으로 올려주신 발표자료는 모두 다운로드 하였습니다 :)
이후 수정하신 분들은 댓글로 따로 알려주세요!

아직 발표자료를 올리지 않은 분들은 빠르게 부탁드릴께요~

**Comment by akakakakakaa** [comment]
AR - Trace 팀 발표자료 업로드 합니다.
[AR-Trace.pdf](https://github.com/D2CAMPUS-FEST/2016/files/782066/AR-Trace.pdf)

**Comment by PJunhyuk** [comment]
crafty 팀 발표자료 업데이트 합니다.
[crafty_D2_presentation_v2.pdf](https://github.com/D2CAMPUS-FEST/2016/files/782245/crafty_D2_presentation_v2.pdf)

**Comment by Kang-heesuk** [comment]
[수상팀 팀 로고]
![kokoto](https://cloud.githubusercontent.com/assets/1983469/23346158/fce13d38-fcda-11e6-9ad7-08f66c5a4ea5.png)
![logo-black](https://cloud.githubusercontent.com/assets/1983469/23346160/fee68fca-fcda-11e6-941d-0524adc2a909.png)
![logo](https://cloud.githubusercontent.com/assets/1983469/23346162/00fd1ce8-fcdb-11e6-9d5b-eaeb88bd766a.png)
