### ISSUE TITLE
[tracer] 실행이후 ipynb 파일이 저장 되지 않습니다.

### ISSUE THREAD

**Issue by hahnlee** [D2CAMPUS-FEST/2016#3]
제 프로젝트의 이슈는
https://github.com/sn0wle0pard/tracer/issues/5
입니다.

IPynb는 json 기반의 파일인데 IPython/Jupyter Notebok에서 실행된뒤 나온 output과 코드를 json파일로 저장합니다. 정확히는 ChartTracer 실행후에 json으로 바꾸는 과정에서 문제가 생깁니다.

**Comment by g6123** [comment]
에러 메시지의 `circular structure`는 아래 코드처럼 JSON이 상호 참조하는 순환 구조일 때를 의미합니다.

```javascript
const o = { f: null };
const f = { o: null };

o.f = f;
f.o = o;

/*
  { o: { f: [Circular] } }
  { f: { o: [Circular] } }
*/
```

명시적으로 상호 참조하지 않았어도 prototype 수준에서 상호 참조되어 있을 가능성이 있습니다.
`JSON.stringify()` 대신 사용할 수 있는 여러가지 해결 방법이 있겠지만

원본 JSON이 아래와 같다고 할때,
```javascript
const data = {
    foo: 'foo',
    bar: 'bar',
    baz: 'baz'
};
```

**1. 필요한 key만 값을 복사한다.**
```javascript
const newData = {
    foo: data.foo,
    bar: data.bar,
    baz: data.baz
};
```

**2. 1의 작업을 자동화**
```javascript
const newData = {};

['foo', 'bar', 'baz'].forEach(function(key) {
    newData[key] = data[key];
});
```

**3. prototype 수준에서의 순환 참조일 때에 한해서는,**
```javascript
const newData = {};

Object.keys(data).forEach(function(key) {
    newData[key] = data[key];
});
```

**Comment by hahnlee** [comment]
오 그렇군요 자바스크립트 코드를 확인해 봐야 겠습니다. 감사합니다 :)

**Comment by hahnlee** [comment]
해결했습니다 감사합니다 :)
