### ISSUE TITLE
[coding-night-live] Websocket with django

### ISSUE THREAD

**Issue by punkyoon** [D2CAMPUS-FEST/2016#4]
https://github.com/punkyoon/coding-night-live

django 최신(1.10)까지는 default로는 wsgi + single connection + sqlite를 지원합니다.
socketio는 asgi + multiple connection + redis와 같은 sqlite보다 훨씬 빠른 db를 사용합니다.
위를 해결하기 위해 찾아본 조합들은 다음과 같습니다.

## 기술 스택
- [django channels](https://github.com/django/channels) (redis)
- [django-socketio](https://github.com/stephenmcd/django-socketio) (socket.io 0.6 out of date, python 3.6 지원 x)
- [django-gevent](https://github.com/abourget/gevent-socketio)
- [django + tornado](http://www.tornadoweb.org/en/stable/wsgi.html)
- [django + twisted](https://ferretfarmer.net/2013/09/05/tutorial-real-time-chat-with-django-twisted-and-websockets-part-1/)
- [sharedb](https://github.com/share/sharedb) (succeding sharejs)
- [hendrix](https://github.com/hendrix/hendrix)
- [django-socketio-events](https://github.com/pztrick/django-socketio-events/)
- [nodejs + django](http://www.cuelogic.com/blog/how-to-use-both-django-nodejs-as-backend-for-your-application/)
- ...

## 지원하거나 지원했으면 좋을 기능들
- live collaborative text edit & chat(+답글)이 가능한 속도와 안정성
- 현재 django 구조에 이어 붙일 수 있는 형태 (compat 등)
- 각 chatting 내용을 서버에 저장
- 정상적으로 저장되었는지 ack 기능 (Google drive에서 저장되지 않는 경우 notify되는 것처럼)

**Comment by bethesirius** [comment]
혹시 AWS로 프로젝트를 이전 하실 계획이 있으시다면, 굳이 웹소켓을 django에서 처리하지 않고 API gate+lambda로 처리하는 방법도 고려해 보시면 어떨까요?

**Comment by punkyoon** [comment]
https://github.com/andrewgodwin/channels-examples/tree/master/multichat/chat
> django와 channels를 이용하여 websocket을 사용한 예제입니다(채팅).

https://github.com/andrewgodwin/channels-examples/
> 채팅 이외에도 다른 예제들도 확인할 수 있습니다.

이슈 해결의 실마리를 찾은 듯 합니다! 기존에 channels를 이용한 예제 코드들은 제대로 동작하지 않는 경우가 많았는데, 위의 예제들은 잘 만들어져서 잘 돌아가네요!
