### ISSUE TITLE
[kokoto] 보안취약점

### ISSUE THREAD

**Issue by Luavis** [D2CAMPUS-FEST/2016#5]
[config.js](https://github.com/hatamake/kokoto/blob/master/config.js) 파일은 가려주세요. ㅎㅎ
![image](https://cloud.githubusercontent.com/assets/1534596/21918189/189ad3e8-d992-11e6-83d0-4e0d10cad2cd.png)

**Comment by hahnlee** [comment]
덧붙여 config.js 대신 config.js.sample파일을 만들어 제공하면 좋을 것 같습니다.

**Comment by g6123** [comment]
그렇네요. 지금의 `config.js`에서 내용을 지우고 Repo.에는 `config.example.js`만 남기는 게 좋겠네요.

\* 사실 현재의 `config.js` 파일에는 [mLab](http://mlab.com/)에 생성한 테스트용 DB가 등록되어 있어서 큰 상관은 없어요/

**Comment by g6123** [comment]
해결됐습니다! [b9f6c8a](https://github.com/hatamake/kokoto/commit/b9f6c8af560a352a2245125b448f5987753f67a5)

**Comment by g6123** [comment]
다른 문제가 없다면 Close 할까요?
