### ISSUE TITLE
[Lighthouse] Event Driven GUI programming 

### ISSUE THREAD

**Issue by Red-Portal** [D2CAMPUS-FEST/2016#8]
복잡한 EDP 기반 GUI 프로그래밍에 대해 아는게 너무 적어서..  관련 자료를 알고 있거나,
예시가 될만한 코드 링크를 공유해주실 수 있다면 정말 감사할 것 같습니다.

**Comment by Luavis** [comment]
[링크](https://courses.cs.washington.edu/courses/cse331/13sp/lectures/lect24-events.pdf) 하나 첨부해보는데 조금 더 질문을 정확히 적어주세요.. 어떤게 이해가 안가는지요..

**Comment by Red-Portal** [comment]
그 동안 다른 일 때문에 바빠서 확인을 못했습니다. 죄송합니다. 이벤트 드리븐 프로그래밍 말고 리액트에서 착안한 방법으로 한번 GUI 구현을 해볼 생각입니다.
